quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=municipal_db
quarkus.http.host=0.0.0.0
# Autorizar a comunicação com o Frontend
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with